Repository hisublime/Project-STBI-5-2, pull requests merged in 2022-06, with the labels that each got.

#8 Friends Dialogue
  01 - Dataset/Friends dialogues.csv
  02 - Code/Proyek_Dataset_Friends-BM11 VS BM25.ipynb
  BM25 V.1/.gitignore
  BM25 V.1/README.md
  BM25 V.1/bm25.py
  BM25 V.1/requirements.txt
  BM25 V.1/sample.py
  BM25 V.1/setup.sh
  BM25 V.2/rank.py
  BM25 V.3/.github/workflows/pytest.yml
  BM25 V.3/.github/workflows/python-publish.yml
  BM25 V.3/.gitignore
  BM25 V.3/CITATION
  BM25 V.3/LICENSE
  BM25 V.3/README.md
  BM25 V.3/rank_bm25.py
  BM25 V.3/requirements.txt
  BM25 V.3/setup.py
  BM25 V.3/tests/test_loading.py
  BM25 V.3/version.py
Labels: enhancement

#12 Upload Document
  03 - Document/Analysis_Comparison_of_BM11_with_BM25.pdf
Labels: documentation

#13 Update Analysis_Comparison_of_BM11_with_BM25.pdf
  03 - Document/Analysis_Comparison_of_BM11_with_BM25.pdf
Labels: bug, enhancement

#15 NewCode
  02 - Code/Proyek_Dataset_Friends-BM11 VS BM25.ipynb
  02 - Code/Proyek_Dataset_TaylorSwift-BM11 VS BM25.ipynb
Labels: enhancement
